dev:
  php:
    executable: C:\dev\php\5614\php.exe
  js:
    dir: ./web/src/js
  typescript:
    enabled: true
    dir: ./web/src/ts/
    output: ./web/src/js
  css:
    dir: ./web/src/css
  less:
    enabled: true
    dir: ./web/src/less
    output: ./web/src/css
  sass:
    enabled: true
    dir: ./web/src/sass
    output: ./web/src/css
  livereload:
    enabled: true
    port: {{livereload_port}}
    livereload_file: ./web/index.html #file where <script> for livereload is located
  server:
    enabled: true
    host: 127.0.0.1:{{server_port}}